"""
Churn model architecture.

This file is intentionally a verbatim mirror of Day 2's `model.py`
(~/churn-predictor/backend/model.py) so Day 3 retraining produces models
that load cleanly into Day 2's serving code AND so Day 3's MLOps service
is self-contained (no cross-repo imports at deploy time).

DO NOT edit this file independently. If Day 2's architecture ever changes,
update both repos together. Keeping the architectures identical is what
makes champion vs challenger comparisons meaningful — same architecture,
trained on different data, judged by the same metric.

Architecture:
  - 12 input features (must match Day 2's FEATURE_COLUMNS)
  - 2 hidden layers (32 -> 16 units) with ReLU + BatchNorm + Dropout
  - 1 output logit (apply sigmoid for probability)

Training note for Phase 3 retrain.py:
  - During training, the model must be in .train() mode for BatchNorm
    to update its running stats. Do NOT call predict_proba() inside the
    training loop — it switches to .eval() mode and will not switch back.
"""
from __future__ import annotations
import torch
import torch.nn as nn


class ChurnNet(nn.Module):
    """Feed-forward network for binary churn classification."""

    def __init__(self, input_dim: int = 12, hidden1: int = 32, hidden2: int = 16, dropout: float = 0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden1),
            nn.BatchNorm1d(hidden1),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden1, hidden2),
            nn.BatchNorm1d(hidden2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden2, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Returns logits (apply sigmoid externally for probability)."""
        return self.net(x)

    def predict_proba(self, x: torch.Tensor) -> torch.Tensor:
        """
        Returns churn probability in [0, 1]. INFERENCE ONLY — flips the
        model into eval() mode and does not restore train(). See module
        docstring for the training-loop guidance.
        """
        self.eval()
        with torch.no_grad():
            return torch.sigmoid(self.forward(x))
